// Auto-generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async initApp() : Promise<void> {
    await TAURI_INVOKE("init_app");
},
async getAllGames() : Promise<GameMetadata[]> {
    return await TAURI_INVOKE("get_all_games");
},
async addLocalGame(path: string) : Promise<Result<GameMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_local_game", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGame(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_game", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGame(game: GameMetadata) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchVndb(query: string) : Promise<Result<VndbSearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_vndb", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchVndbDetail(vndbId: string, forceRefresh: boolean | null) : Promise<Result<VndbVnDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_vndb_detail", { vndbId, forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchVndbCharacters(vndbId: string, forceRefresh: boolean | null) : Promise<Result<VndbCharacter[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_vndb_characters", { vndbId, forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearVndbCache(vndbId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_vndb_cache", { vndbId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async saveVndbToken(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_vndb_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearVndbToken() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_vndb_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setBlurNsfw(blur: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_blur_nsfw", { blur }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbAuthCheck() : Promise<Result<VndbAuthInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_auth_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbGetUserVn(vndbId: string) : Promise<Result<VndbUserListItem | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_get_user_vn", { vndbId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbSetStatus(vndbId: string, labelId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_set_status", { vndbId, labelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbSetVote(vndbId: string, vote: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_set_vote", { vndbId, vote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbRemoveVote(vndbId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_remove_vote", { vndbId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchGame(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_game", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTracking() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_tracking") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pollRunningGame() : Promise<string | null> {
    return await TAURI_INVOKE("poll_running_game");
},
async getElapsedTime() : Promise<number> {
    return await TAURI_INVOKE("get_elapsed_time");
},
async setGameHidden(id: string, hidden: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_hidden", { id, hidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { vndb_token: string | null; vndb_user_id: string | null; blur_nsfw: boolean }
export type DailyPlaytimeData = { games: Partial<{ [key in string]: Partial<{ [key in string]: number }> }> }
export type GameMetadata = { id: string; title: string; path: string; vndb_id: string | null; cover_url: string | null; play_time: number; is_finished: boolean; last_played?: string | null; is_hidden?: boolean }
export type VndbAuthInfo = { id: string; username: string }
export type VndbCharacter = { id: string; name: string; original: string | null; aliases: string[] | null; image: VndbImage | null; description: string | null; blood_type: string | null; height: number | null; weight: number | null; bust: number | null; waist: number | null; hips: number | null; cup: string | null; age: number | null; birthday: number[] | null; sex: string[] | null; vns: VndbCharacterVn[] | null; traits: VndbTrait[] | null }
export type VndbCharacterVn = { id: string; role: string; spoiler?: number }
export type VndbImage = { url: string; sexual?: number; violence?: number }
export type VndbLabel = { id: number; label: string }
export type VndbSearchResult = { id: string; title: string; image: VndbImage | null; released: string | null; rating: number | null }
export type VndbTag = { id: string; name: string; rating: number; spoiler?: number }
export type VndbTrait = { id: string; name: string; group_id: string | null; group_name: string | null; spoiler?: number }
export type VndbUserListItem = { id: string; vote: number | null; labels: VndbLabel[] | null; started: string | null; finished: string | null }
export type VndbVnDetail = { id: string; title: string; image: VndbImage | null; released: string | null; rating: number | null; description: string | null; length: number | null; length_minutes: number | null; tags: VndbTag[] | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
